site_name: FastANI
site_description: FastANI documentation
docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy

markdown_extensions:
  - admonition
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Home: index.md
